task:
  name: "00_cartpole"
  physics_engine: physx
  env:
    num_envs: 5000
    env_spacing: 5
    max_episode_length: 1000
    
  sim:
    substeps: 2

  task: 
    randomize: True


policy: 
    name: "SimpleActorCritic"
    
    action_std: # hard set the std -> if this is not set, or set to 'auto' the action_std becomes a parameter
      schedule_type: 'steps'
      interpolation: 'none'
      schedule: 
        10e6: 1e-4
        20e6: 1e-5
        30e6: 8e-5
    
    actor_hidden_layers:
      - 64
      - 64
      - 64
    critic_hidden_layers:
      - 64
      - 64
    lr: 1e-5

    


algo:
  name: "PPO" 
  gamma: 0.99
  n_epochs: 5
  eps_clip: 0.2
  n_steps: 200 # the amount of steps taken per env between training and update
  batch_size: 1000
  target_kl: 0.008
  gae_lamda: 0.5
  entropy_coef: 0
  value_f_coef: 1

