
seed: 42

#start_model: 'start_models/02_mk1_walking.pth'

task:
  name: "03_mk1_controlled"

  vec_task: 
    num_envs: 1024
    max_episode_length: 1500
    

  mk1: 
    pure_shapes: False

    spawn_height: 1.65
    initial_velocities: 
        - {
          dist_type: 'gaussian',
          mean: 0,
          std: 0.0
        }
        - { # The y direction is the direction the agent is facing at the beginning
            dist_type: 'gaussian',
            mean: -0.5,
            std: 0.0
          }
        - 0


    agent:
      default_motor_power: 1000 
      motor_powers: # describe by using joint name and than the max efort in NM
        left_foot: 300
        left_knee: 1500
        left_hip_b: 1000
        left_hip_a: 1000
        
        right_foot: 300
        right_knee: 1500
        right_hip_b: 500
        right_hip_a: 500

        torso: 300

        left_elbow: 400
        left_arm_rotate: 200
        left_shoulder_b: 400
        left_shoulder_a: 400

        right_elbow: 400
        right_arm_rotate: 200
        right_shoulder_b: 400
        right_shoulder_a: 400

      default_friction: 
        dist_type: gaussian
        mean: 100
        std: 3
      frictions: # describe by using the link name 
        foot: 
          dist_type: gaussian
          mean: 400
          std: 10
        foot_2: 
          dist_type: gaussian
          mean: 400
          std: 10


      # mass stamdard deviation  
      default_mass_std: 0.3 # nothing above 0.17 is advised 


   


policy: 

  normalize_input: True

  actor_net:
    - name: actor_linear_obs_net
      input: 
          - obs: linear
          - obs: command
      mlp:
          units: [512, 512,  256, 128]
          activation: elu
          initializer: default



algo:
  name: "PPO"
  grad_norm: 1.0
  gamma: 0.99
  mixed_precision: True
  gae_lambda: 0.95
  truncate_grads: True
  normalize_value: True 
  normalize_advantage: True
  value_size: 1 # the amount of values the critic outputs
  weight_decay: 0.0
  learning_rate: 5e-4
  lr_schedule: adaptive
  kl_threshold: 0.008
  e_clip: 0.2
  clip_value: True
  horizon_length: 32
  minibatch_size: 32768
  mini_epochs: 5
  reward_shaper:
    scale_value: 0.01
    shift_value: 0

  value_bootstrap: True
  critic_coef: 4
  entropy_coef: 0

  bounds_loss_coef: 0.0001


  delayed_training: False



