wandb_version: 1

name:
  desc: null
  value: PPO
grad_norm:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.99
mixed_precision:
  desc: null
  value: true
gae_lambda:
  desc: null
  value: 0.95
truncate_grads:
  desc: null
  value: true
normalize_value:
  desc: null
  value: true
normalize_advantage:
  desc: null
  value: true
value_size:
  desc: null
  value: 1
weight_decay:
  desc: null
  value: 0.0
learning_rate:
  desc: null
  value: 5e-4
lr_schedule:
  desc: null
  value: adaptive
kl_threshold:
  desc: null
  value: 0.008
e_clip:
  desc: null
  value: 0.2
clip_value:
  desc: null
  value: true
horizon_length:
  desc: null
  value: 32
minibatch_size:
  desc: null
  value: 32768
mini_epochs:
  desc: null
  value: 5
reward_shaper:
  desc: null
  value:
    scale_value: 0.01
    shift_value: 0
value_bootstrap:
  desc: null
  value: true
critic_coef:
  desc: null
  value: 4
entropy_coef:
  desc: null
  value: 0
bounds_loss_coef:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.8.15
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690983566.054992
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 14
      - 16
      - 23
      4: 3.8.15
      5: 0.15.7
      8:
      - 5
