# Configuaration file for the walking task
# There are no universal "episodes" since every actor can terminate an episode prematurely
# This is the standard configuration for the walking env
# every value can be overwritten by the config in the constructor


name: 01_walking


walking:

  reward_weighting:
    directional_factor: 10
    death_cost: 2
    energy_cost: 0.5
    alive_reward: 0.2


    
    
