gamma: 0.99
lr: 1e-5
n_epochs: 3
eps_clip: 0.1
n_steps: 200 # the amount of steps taken per env between training and update
batch_size: 1000
target_kl: 0.1
gae_lamda: 0.5
entropy_coef: 0.000
value_f_coef: 1


