gamma: 0.99
lr: 1e-4
n_epochs: 10
eps_clip: 0.1
n_steps: 100
batch_size: 100
target_kl: 0.1
gae_lamda: 0.5

# action standard devisation schedule with timestep taken in the environment
action_std: {
  schedule_type: 'steps', 
  schedule: [ 
    [0, 0.5],
    [1000, 0.4],
    [2000, 0.3],
    [3000, 0.2],
    [10000, 0.1]
  ]
}
