# Configuaration file for the walking task
# There are no universal "episodes" since every actor can terminate an episode prematurely
# This is the standard configuration for the walking env
# every value can be overwritten by the config in the constructor


name: "06_mk1_controlled_terrain"

mk1_controlled_terrain:

  controls:
 
    direction_x: 
      mean: 1
      std: 0
      dist_type: gaussian

    direction_y:
      mean: -1
      std: 0 
      dist_type: gaussian
    
    velocity:
      dist_type: linear_drawn
      values: [0,4]

  reward_weighting:

      death_height: 1.25 # the height of the base at which the episode is terminated and the actor is considered dead
      directional_factor: 0.8
      zero_clip_direction_reward: True
      death_cost: 10
      energy_cost: 0.005
      alive_reward: 2
      upright_punishment_factor: 0.1 # higher values punish the actor more for bad posture
      die_not_upward: True
      
      jitter_cost: 0.25
      overextend_cost: 4

      arm_use_cost: 1

      target_velocity_factor: 2.0
      slowdown_punish_difference: 0.6 # the point when being to fast will be punished
      # note any speed slower than the target speed will be rewarded, only negative speed will be punished proportionally
      forward_facing_vel_factor: 0.5 # rewards, that the velocity is in the forward direction
      target_facing_vel_factor: 0.0 # rewards, that the velcoity is in the target direction

      die_on_contact: False # die when anything other than the foot touches the ground
      contact_punishment: 3 # punsihment if anyhing other than feet touvh the ground only usefull if die_on_contact is of

  terrain:
        terrainType: trimesh # none, plane, or trimesh
        staticFriction: 1.0  # [-]
        dynamicFriction: 1.0  # [-]
        restitution: 0.        # [-]
        # rough terrain only:
        curriculum: True
        maxInitMapLevel: 0
        mapLength: 8.
        mapWidth: 8.
        numLevels: 10
        numTerrains: 20
        # terrain types: [smooth slope, rough slope, stairs up, stairs down, discrete]
        terrainProportions: [0.1, 0.1, 0.35, 0.25, 0.2]
        # tri mesh only:
        slopeTreshold: 0.5


# vec_task:
#   sim: 
#     physx: 
#       max_gpu_contact_pairs: 16777216 # 8*1024*1024
