# Configuaration file for the walking task

name: 01_walking

physics_engine: physx

env: 
  numEnvs: 100
  envSpacing: 5
  episodeLength: 1000 

sim:
  dt: 0.0166 # 1/60 s
  substeps: 2
  up_axis: "z"
  use_gpu_pipeline: True
  gravity: [0.0, 0.0, -9.81]

task: 
  randomize: False