# Configuaration file for the walking task
# There are no universal "episodes" since every actor can terminate an episode prematurely
# This is the standard configuration for the walking env
# every value can be overwritten by the config in the constructor


name: "02_mk1_walking"

mk1_walking:
  reward_weighting:

      death_height: 1.25 # the height of the base at which the episode is terminated and the actor is considered dead
      directional_factor: 0.8
      zero_clip_direction_reward: True
      death_cost: 10
      energy_cost: 0.005
      alive_reward: 2
      upright_punishment_factor: 20 # higher values punish the actor more for bad posture
      jitter_cost: 0.25
      overextend_cost: 4


      arm_use_cost: 1


      die_on_contact: False # die when anything other than the foot touches the ground
      contact_punishment: 3 # punsihment if anyhing other than feet touvh the ground only usefull if die_on_contact is of


