{algo: {bounds_loss_coef: 0.0001, clip_value: true, critic_coef: 4, e_clip: 0.2, entropy_coef: 0,
    gae_lambda: 0.95, gamma: 0.99, grad_norm: 1.0, horizon_length: 32, kl_threshold: 0.008,
    learning_rate: 5e-4, lr_schedule: adaptive, mini_epochs: 5, minibatch_size: 32768,
    mixed_precision: true, name: PPO, normalize_advantage: true, normalize_value: true,
    reward_shaper: {scale_value: 0.01, shift_value: 0}, truncate_grads: true, value_bootstrap: true,
    value_size: 1, weight_decay: 0.0}, policy: {actor_net: [{input: [{obs: linear},
          {obs: command}], mlp: {activation: elu, initializer: default, units: [512,
            512, 256, 128]}, name: actor_linear_obs_net}], normalize_input: true},
  seed: 42, task: {mk1: {agent: {default_friction: {dist_type: gaussian, mean: 50,
          std: 2}, default_mass_std: 0.1, default_motor_power: 1000, frictions: {
          foot: {dist_type: gaussian, mean: 100, std: 3}, foot_2: {dist_type: gaussian,
            mean: 100, std: 3}}, motor_powers: {left_arm_rotate: 200, left_elbow: 400,
          left_foot: 300, left_hip_a: 1000, left_hip_b: 1000, left_knee: 1500, left_shoulder_a: 400,
          left_shoulder_b: 400, right_arm_rotate: 200, right_elbow: 400, right_foot: 300,
          right_hip_a: 500, right_hip_b: 500, right_knee: 1500, right_shoulder_a: 400,
          right_shoulder_b: 400, torso: 300}}, initial_velocities: [{dist_type: gaussian,
          mean: 0, std: 0.0}, {dist_type: gaussian, mean: -0.5, std: 0.0}, 0], pure_shapes: false,
      spawn_height: 1.65}, name: 03_mk1_controlled, vec_task: {max_episode_length: 3000,
      num_envs: 1024}}}
