


  policy:
    name: actor_critic

    mu_activation: None
    sigma_activation: None
    mu_init:
      name: default
    sigma_init:
      name: const_initializer
      val: 0
    fixed_sigma: True

    actor:
      units: [256, 128, 64]
      activation: relu
      initializer:
        name: default
        scale: 2

    critic:
        
    

    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256,128,64]
      d2rl: False
      activation: relu
      initializer:
        name: default
        scale: 2         