# Configuaration file for the walking task
# There are no universal "episodes" since every actor can terminate an episode prematurely
# This is the standard configuration for the walking env
# every value can be overwritten by the config in the constructor


name: "04_mk1_multitask"

mk1_multitask:
  reward_weighting:

      

      to_target_prob: 1.0
      to_target:
        death_height: 1.25 # the height of the base at which the episode is terminated and the actor is considered dead
        death_cost: 80      
        forward_directional_factor: 0.8
        zero_clip_direction_reward: True
        energy_cost: 0.005
        alive_reward: 2
        upright_punishment_factor: 20 # higher values punish the actor more for bad posture
        jitter_cost: 0.25
        overextend_cost: 4

        velocity_reward_factor: 0.0


        die_on_contact: False # die when anything other than the foot touches the ground
        contact_punishment: 0 # punsihment if anyhing other than feet touvh the ground only usefull if die_on_contact is of

      idle_prob: 0.0
      idle:
        death_height: 1.25 # the height of the base at which the episode is terminated and the actor is considered dead
        death_cost: 160      
        forward_directional_factor: 0.8
        zero_clip_direction_reward: True
        energy_cost: 0.01
        alive_reward: 3
        upright_punishment_factor: 20 # higher values punish the actor more for bad posture
        jitter_cost: 0.50
        overextend_cost: 0.1
        velocity_reward_factor: -3.0


        die_on_contact: True # die when anything other than the foot touches the ground
        contact_punishment: 3 # punsihment if anyhing other than feet touvh the ground only usefull if die_on_contact is of



mk1:

  pure_shapes: False

  spawn_height: 1.65
  initial_velocities: 
      - {
        dist_type: 'gaussian',
        mean: 0,
        std: 0.4
      }
      - { # The y direction is the direction the agent is facing at the beginning
          dist_type: 'gaussian',
          mean: -0.5,
          std: 0.8
        }
      - 0


  agent:
    default_motor_power: 1000 
    motor_powers: # describe by using joint name and than the max efort in NM
      left_foot: 300
      left_knee: 1500
      left_hip_b: 1000
      left_hip_a: 1000
      
      right_foot: 300
      right_knee: 1500
      right_hip_b: 500
      right_hip_a: 500

      torso: 300

      left_elbow: 400
      left_arm_rotate: 200
      left_shoulder_b: 400
      left_shoulder_a: 400

      right_elbow: 400
      right_arm_rotate: 200
      right_shoulder_b: 400
      right_shoulder_a: 400

    default_friction: 1.0
    frictions: # describe by using the link name 
      foot: 10
      foot_2: 10

    # mass stamdard deviation 
    default_mass_std: 0.0




    
